### ISSUE TITLE
Release successfully created, but build step failed.

### ISSUE THREAD

**Issue by RodolpheFouquet** [drone-plugins/drone-gitea-release#12]
Hi, 

I'm using the gitea release module to push a release and its content to our gitea.

The module seems to successfully push the content to gitea, as you can see here:

![screenshot from 2018-10-10 01-32-08](https://user-images.githubusercontent.com/3400735/46704666-50bd2300-cc2c-11e8-8a74-73270156917a.png)

gitea_release log seems to be indicate that the release was ok, but as you can see here, the build step fails:
![screenshot from 2018-10-10 01-30-40](https://user-images.githubusercontent.com/3400735/46704624-24a1a200-cc2c-11e8-9f53-0c28875a73d9.png)

The version of gitea used is 1.5.1, and the attachement mime types have been configured in the app.ini to allow tar.gz mime types.

**Comment by tboerger** [comment]
Closing because of lacking details
