### ISSUE TITLE
Ability to create release without tag

### ISSUE THREAD

**Issue by rakshith-ravi** [drone-plugins/drone-gitea-release#14]
It would be really appreciated if this plugin could create a release without a tag, but rather on a branch instead. So for example, if this plugin could create a release on pushing to a specific branch, it would make it easier to create releases on that specific branch.

Now I do understand that creating a release requires a tag, but perhaps this plugin could take that as a parameter (or maybe from a file?) and automatically create the tag? That would be very helpful.

The reason I'm requesting for this is because my current git flow is currently very redundant (or maybe I'm doing it wrong). 

User pushes to `develop` branch, makes a PR to `staging` branch. Once it gets merged, drone pulls the branch (it's configured to only build for `staging` and `master` branch), build the application, and do nothing. Then, a tag is separately pushed to the `staging` branch (because tags cannot be a part of the PR, and I personally don't want anyone else to create a tag except for the approving authorities), then drone builds it again and then creates a release. I'd rather prefer it if it automatically builds the project once a push is made to a specific branch and a release is also created automatically.

Please help me understand a better git workflow in case I'm doing it wrong

**Comment by tboerger** [comment]
Sorry, but doing a git tag is out of scope of this plugin. But feel free to fork this plugin and add as much functionality as you want. We encourage people to build specialized plugins tailored to their needs.

**Comment by rakshith-ravi** [comment]
That is understandable, but perhaps you could help me with understanding the intended git flow for something like this?

**Comment by tboerger** [comment]
The intended and pretty regular workflow is like you explained above. Push/merge changes into a branch, create a tag, push the tag.
