### ISSUE TITLE
Lack of 'Target' field in request body

### ISSUE THREAD

**Issue by joyqat** [drone-plugins/drone-gitea-release#17]
This results in
`Failed to create release: 422 Unprocessable Entity: [{\"fieldNames\":[\"Target\"],\"classification\":\"RequiredError\",\"message\":\"Required\"}]"`

Need to update with https://github.com/go-gitea/go-sdk/blob/master/gitea/release.go

**Comment by tboerger** [comment]
Please provide more details because this plugin is working without an issue for me.

**Comment by joyqat** [comment]
Gitea has a 'Target' field in CreateReleaseOption, and this field is marked Required.
https://github.com/go-gitea/go-sdk/blob/master/gitea/release.go#L56

This problem happened when I pushed a tag to git server. This tag didn't have related release, so the plugin will try to create one. When invoking `CreateRelease`, the gitea server will complaint about lacking of 'Target'.
I think this might be related to API change, or some other bugs.

My environment:
 gitea: commit 0756495, private mode
 drone: 1.0.0-rc5

Complete Log:
```
Release test_pub not found
time="2019-01-26T01:15:48Z" level=fatal msg="Failed to create the release. Failed to retrieve or create a release: Failed to create release: 422 Unprocessable Entity: [{\"fieldNames\":[\"Target\"],\"classification\":\"RequiredError\",\"message\":\"Required\"}]"
```

**Comment by joyqat** [comment]
Hi tboerger,
I think gitea has changed the API since [this commit](https://github.com/go-gitea/go-sdk/commit/6abdddefe30bd2941f98d50ae5efc6154aa7fa85)

**Comment by joyqat** [comment]
That commit was reverted so this issue might be resolved
