### ISSUE TITLE
Failed to upload files

### ISSUE THREAD

**Issue by kinosang** [drone-plugins/drone-gitea-release#21]
like #7 

Releases created successfully, but attachments cannot be uploaded.

Got `Failed to upload the files. Failed to upload xxx artifact: invalid character '<' looking for beginning of value`

Gitea app.ini
```ini
APP_NAME = Gitea
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
PASSWD   =
SSL_MODE = disable
PATH     = data/gitea.db

[repository]
ROOT = /var/data/gitea/repositories

[server]
DOMAIN           = *REMOVED*
HTTP_PORT        = 3000
ROOT_URL         = *REMOVED*
DISABLE_SSH      = false
SSH_PORT         = 22
SSH_LISTEN_PORT  = 2222
START_SSH_SERVER = true
OFFLINE_MODE     = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = true

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[attachment]
ALLOWED_TYPES = */*
MAX_SIZE = 4096

[log]
MODE      = file
LEVEL     = INFO
ROOT_PATH = /var/data/gitea/log

[security]
INSTALL_LOCK   = true
SECRET_KEY     = *REMOVED*
INTERNAL_TOKEN = *REMOVED*
[oauth2]
JWT_SECRET = *REMOVED*
```

**Comment by tboerger** [comment]
It's a different issue than on the linked issue. The error indicates that the response from gitea isn't formatted in json format, which quite often comes from wrong gitea urls or if the gitea server tries to redirect from http to https.

**Comment by kinosang** [comment]
It's solved after re-config HTTPS for Gitea (follow [this](https://docs.gitea.io/en-us/https-setup/)).

Cuz I just migrated from Gogs (HTTPS via Nginx with 301 redirect from HTTP)
