### ISSUE TITLE
gitea docs for checksum indent error

### ISSUE THREAD

**Issue by fanlix** [drone-plugins/drone-gitea-release#22]
in doc from http://plugins.drone.io/drone-plugins/drone-gitea-release/
the yaml with checksum example has a little syntax error:

> indent of **checksum** line should belong under **settings**

easy to fix:  lacks of a whitespace

**Comment by techknowlogick** [comment]
Thanks for this issue. Please open a PR here: https://github.com/drone/drone-plugin-index as that is where plugins.drone.io lives.
