### ISSUE TITLE
Content type error

### ISSUE THREAD

**Issue by atoy40** [drone-plugins/drone-gitea-release#6]
Hello,

I'm trying to push some release to gitea, but I get the following error :
```File type is not allowed```
The file I've uploaded is a .tar.gz file, which is supposed to have the application/gzip mime type, and this type is in the default list of allowed type in gitea setting.

Any idea ?

**Comment by tboerger** [comment]
That sounds like an upstream gitea issue, this plugin just uses the gitea go sdk. So please report it on the gitea forum or issue tracker to get support for that.

**Comment by jonasfranz** [comment]
You can try to allow all file types for testing.

**Comment by atoy40** [comment]
@JonasFranzDEV how do you do that ? the config parameter accept wildcard ?
Anthony.

**Comment by jonasfranz** [comment]
@atoy40 https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment

**Comment by tboerger** [comment]
Issue seems to be solved
