### ISSUE TITLE
Missing support of checksum files

### ISSUE THREAD

**Issue by typeless** [drone-plugins/drone-gitea-release#9]
The plugin doesn't work if I add the `checksum` parameter to `.drone.yml`.  The logs I added show that it's due to the .txt file for the checksum is not in the set of `allowedTypes`.

It's not a necessary parameter for me but I think having the issue open here can save others' time from diagnosing it.

**Comment by tboerger** [comment]
Just to get your reported issue right, the checksum text file is not allowed on your Gitea instance? Than I wouldn't call that an issue on the side of this plugin as this can't change the allowed files on your Gitea instance.

**Comment by typeless** [comment]
I expected that there would be a mysterious type in the `allowedType` set that the checksum files of this plugin can be fitted in. 

I can file an issue to Gitea too.

**Comment by tboerger** [comment]
You have to allow the mime type for text files within your Gitea app.ini (setting ALLOWED_TYPES, for reference: https://docs.gitea.io/en-us/config-cheat-sheet/#attachment-attachment)
